# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 710)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSignUp = QtWidgets.QPushButton(self.centralwidget)
        self.btnSignUp.setGeometry(QtCore.QRect(80, 590, 381, 81))
        self.btnSignUp.setObjectName("btnSignUp")
        self.btnSignIn = QtWidgets.QPushButton(self.centralwidget)
        self.btnSignIn.setGeometry(QtCore.QRect(80, 450, 381, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.btnSignIn.setFont(font)
        self.btnSignIn.setObjectName("btnSignIn")
        self.labelHeader = QtWidgets.QLabel(self.centralwidget)
        self.labelHeader.setGeometry(QtCore.QRect(110, 20, 301, 34))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.labelHeader.setFont(font)
        self.labelHeader.setObjectName("labelHeader")
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setGeometry(QtCore.QRect(110, 560, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelInfo.setFont(font)
        self.labelInfo.setObjectName("labelInfo")
        self.labelCamera = QtWidgets.QLabel(self.centralwidget)
        self.labelCamera.setGeometry(QtCore.QRect(100, 60, 351, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCamera.sizePolicy().hasHeightForWidth())
        self.labelCamera.setSizePolicy(sizePolicy)
        self.labelCamera.setText("")
        self.labelCamera.setObjectName("labelCamera")
        self.labelLName = QtWidgets.QLabel(self.centralwidget)
        self.labelLName.setGeometry(QtCore.QRect(120, 460, 72, 19))
        self.labelLName.setObjectName("labelLName")
        self.lineEditPhone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPhone.setGeometry(QtCore.QRect(260, 560, 176, 25))
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.lineEditLName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLName.setGeometry(QtCore.QRect(260, 460, 176, 25))
        self.lineEditLName.setObjectName("lineEditLName")
        self.lineEditMName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMName.setGeometry(QtCore.QRect(260, 510, 176, 25))
        self.lineEditMName.setObjectName("lineEditMName")
        self.labelPhone = QtWidgets.QLabel(self.centralwidget)
        self.labelPhone.setGeometry(QtCore.QRect(120, 560, 44, 19))
        self.labelPhone.setObjectName("labelPhone")
        self.lineEditFName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFName.setGeometry(QtCore.QRect(260, 410, 176, 25))
        self.lineEditFName.setObjectName("lineEditFName")
        self.btnSignUp_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnSignUp_2.setGeometry(QtCore.QRect(110, 610, 331, 61))
        self.btnSignUp_2.setObjectName("btnSignUp_2")
        self.labelHeader_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelHeader_2.setGeometry(QtCore.QRect(110, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelHeader_2.setFont(font)
        self.labelHeader_2.setObjectName("labelHeader_2")
        self.labelFName = QtWidgets.QLabel(self.centralwidget)
        self.labelFName.setGeometry(QtCore.QRect(120, 420, 74, 19))
        self.labelFName.setObjectName("labelFName")
        self.labelMName = QtWidgets.QLabel(self.centralwidget)
        self.labelMName.setGeometry(QtCore.QRect(120, 510, 90, 19))
        self.labelMName.setObjectName("labelMName")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Library Login"))
        self.btnSignUp.setText(_translate("MainWindow", "Sign up"))
        self.btnSignIn.setText(_translate("MainWindow", "Sign in"))
        self.labelHeader.setText(_translate("MainWindow", "Sign in to Smart Library"))
        self.labelInfo.setText(_translate("MainWindow", "If you are not a member:"))
        self.labelLName.setText(_translate("MainWindow", "Last name"))
        self.labelPhone.setText(_translate("MainWindow", "Phone"))
        self.btnSignUp_2.setText(_translate("MainWindow", "Sign up for Smart Library"))
        self.labelHeader_2.setText(_translate("MainWindow", "Join Smart Library"))
        self.labelFName.setText(_translate("MainWindow", "First name"))
        self.labelMName.setText(_translate("MainWindow", "Middle name"))

