# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 721)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSignUp = QtWidgets.QPushButton(self.centralwidget)
        self.btnSignUp.setEnabled(True)
        self.btnSignUp.setGeometry(QtCore.QRect(80, 590, 381, 81))
        self.btnSignUp.setObjectName("btnSignUp")
        self.labelHeader = QtWidgets.QLabel(self.centralwidget)
        self.labelHeader.setGeometry(QtCore.QRect(130, 10, 301, 34))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.labelHeader.setFont(font)
        self.labelHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader.setObjectName("labelHeader")
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setGeometry(QtCore.QRect(110, 560, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelInfo.setFont(font)
        self.labelInfo.setObjectName("labelInfo")
        self.labelCamera = QtWidgets.QLabel(self.centralwidget)
        self.labelCamera.setGeometry(QtCore.QRect(30, 50, 472, 354))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCamera.sizePolicy().hasHeightForWidth())
        self.labelCamera.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelCamera.setFont(font)
        self.labelCamera.setText("")
        self.labelCamera.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelCamera.setObjectName("labelCamera")
        self.btnSignUp2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnSignUp2.setEnabled(False)
        self.btnSignUp2.setGeometry(QtCore.QRect(80, 620, 381, 61))
        self.btnSignUp2.setObjectName("btnSignUp2")
        self.labelHeader2 = QtWidgets.QLabel(self.centralwidget)
        self.labelHeader2.setGeometry(QtCore.QRect(170, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelHeader2.setFont(font)
        self.labelHeader2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader2.setObjectName("labelHeader2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 400, 381, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditFName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFName.setObjectName("lineEditFName")
        self.gridLayout.addWidget(self.lineEditFName, 0, 1, 1, 1)
        self.labelLName = QtWidgets.QLabel(self.layoutWidget)
        self.labelLName.setObjectName("labelLName")
        self.gridLayout.addWidget(self.labelLName, 1, 0, 1, 1)
        self.lineEditMName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditMName.setObjectName("lineEditMName")
        self.gridLayout.addWidget(self.lineEditMName, 2, 1, 1, 1)
        self.lineEditLName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditLName.setObjectName("lineEditLName")
        self.gridLayout.addWidget(self.lineEditLName, 1, 1, 1, 1)
        self.labelMName = QtWidgets.QLabel(self.layoutWidget)
        self.labelMName.setObjectName("labelMName")
        self.gridLayout.addWidget(self.labelMName, 2, 0, 1, 1)
        self.labelPhone = QtWidgets.QLabel(self.layoutWidget)
        self.labelPhone.setObjectName("labelPhone")
        self.gridLayout.addWidget(self.labelPhone, 3, 0, 1, 1)
        self.lineEditPhone = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.gridLayout.addWidget(self.lineEditPhone, 3, 1, 1, 1)
        self.labelFName = QtWidgets.QLabel(self.layoutWidget)
        self.labelFName.setObjectName("labelFName")
        self.gridLayout.addWidget(self.labelFName, 0, 0, 1, 1)
        self.btnBack = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(0, 0, 111, 52))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("backArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon)
        self.btnBack.setIconSize(QtCore.QSize(30, 30))
        self.btnBack.setObjectName("btnBack")
        self.btnSignIn = QtWidgets.QPushButton(self.centralwidget)
        self.btnSignIn.setEnabled(False)
        self.btnSignIn.setGeometry(QtCore.QRect(80, 470, 381, 81))
        self.btnSignIn.setObjectName("btnSignIn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Library Login"))
        self.btnSignUp.setText(_translate("MainWindow", "Sign up"))
        self.labelHeader.setText(_translate("MainWindow", "Sign in to Smart Library"))
        self.labelInfo.setText(_translate("MainWindow", "If you are not a member:"))
        self.btnSignUp2.setText(_translate("MainWindow", "Sign up for Smart Library"))
        self.labelHeader2.setText(_translate("MainWindow", "Join Smart Library"))
        self.labelLName.setText(_translate("MainWindow", "Last name"))
        self.labelMName.setText(_translate("MainWindow", "Middle name"))
        self.labelPhone.setText(_translate("MainWindow", "Phone"))
        self.labelFName.setText(_translate("MainWindow", "First name"))
        self.btnBack.setText(_translate("MainWindow", "Back"))
        self.btnSignIn.setText(_translate("MainWindow", "Sign In"))

